version: "3"

services:
  mongodb:
    image: mongo:4.0
    container_name: container_db
    command: --replSet rs0
    volumes:
      - ./:/app
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: langDb
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - 27017:27017

networks:
  default:
    name: history_languages_net

    # rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'localhost:27017'}]});